export const pokerogue_pokemonSinnoh_passives = {
  turtwig: "Solid Rock",
  grotle: "Solid Rock",
  torterra: "Thick Fat",
  chimchar: "Unnerve",
  monferno: "Beast Boost",
  infernape: "Beast Boost",
  piplup: "Cute Charm",
  prinplup: "Drizzle",
  empoleon: "Drizzle",
  starly: "Intimidate",
  staravia: "Rock Head",
  staraptor: "Rock Head",
  bidoof: "Sap Sipper",
  bibarel: "Sap Sipper",
  kricketot: "Honey Gather",
  kricketune: "Sharpness",
  shinx: "Speed Boost",
  luxio: "Speed Boost",
  luxray: "Speed Boost",
  budew: "Seed Sower",
  roselia: "Grassy Surge",
  roserade: "Grassy Surge",
  cranidos: "Rock Head",
  rampardos: "Rock Head",
  shieldon: "Earth Eater",
  bastiodon: "Earth Eater",
  burmy: "Sturdy",
  wormadam: "Sturdy",
  mothim: "Speed Boost",
  combee: "Run Away",
  vespiquen: "Intimidate",
  pachirisu: "Honey Gather",
  buizel: "Moxie",
  floatzel: "Moxie",
  cherubi: "Drought",
  cherrim: "Orichalcum Pulse",
  shellos: "Regenerator",
  gastrodon: "Regenerator",
  drifloon: "Magic Guard",
  drifblim: "Magic Guard",
  buneary: "Adaptability",
  lopunny: "Adaptability",
  glameow: "Intimidate",
  purugly: "Intimidate",
  chingling: "Punk Rock",
  chimecho: "Punk Rock",
  stunky: "Neutralizing Gas",
  skuntank: "Neutralizing Gas",
  bronzor: "Mirror Armor",
  bronzong: "Mirror Armor",
  bonsly: "Sap Sipper",
  sudowoodo: "Sap Sipper",
  mime_jr: "Prankster",
  mr_mime: "Prankster",
  galar_mr_mime: "Prankster",
  mr_rime: "Prankster",
  happiny: "Hospitality",
  chansey: "Friend Guard",
  blissey: "Fur Coat",
  chatot: "Punk Rock",
  spiritomb: "Vessel Of Ruin",
  gible: "Arena Trap",
  gabite: "Arena Trap",
  garchomp: "Arena Trap",
  munchlax: "Cheek Pouch",
  snorlax: "Cheek Pouch",
  riolu: "Minds Eye",
  lucario: "Minds Eye",
  hippopotas: "Unaware",
  hippowdon: "Unaware",
  skorupi: "Super Luck",
  drapion: "Super Luck",
  croagunk: "Moxie",
  toxicroak: "Moxie",
  carnivine: "Arena Trap",
  finneon: "Water Bubble",
  lumineon: "Water Bubble",
  mantyke: "Unaware",
  mantine: "Unaware",
  snover: "Slush Rush",
  abomasnow: "Slush Rush",
  rotom: "Hadron Engine",
  uxie: "Magic Bounce",
  mesprit: "Moody",
  azelf: "Neuroforce",
  dialga: "Berserk",
  palkia: "Berserk",
  heatran: "Earth Eater",
  regigigas: "Scrappy",
  giratina: "Shadow Shield",
  cresselia: "Shadow Shield",
  phione: "Simple",
  manaphy: "Primordial Sea",
  darkrai: "Unnerve",
  shaymin: "Grassy Surge",
  arceus: "Adaptability"
}
