export const pokerogue_pokemonJohto_passives = {
    chikorita: "Cute Charm",
    bayleef: "Thick Fat",
    meganium: "Thick Fat",
    cyndaquil: "White Smoke",
    quilava: "Drought",
    typhlosion: "Drought",
    hisui_typhlosion: "Drought",
    totodile: "Strong Jaw",
    croconaw: "Strong Jaw",
    feraligatr: "Strong Jaw",
    sentret: "Pickup",
    furret: "Pickup",
    hoothoot: "Aerilate",
    noctowl: "Aerilate",
    ledyba: "Prankster",
    ledian: "Prankster",
    spinarak: "Prankster",
    ariados: "Prankster",
    chinchou: "Regenerator",
    lanturn: "Regenerator",
    pichu: "Electric Surge",
    pikachu: "Electric Surge",
    raichu: "Electric Surge",
    alola_raichu: "Electric Surge",
    cleffa: "Prankster",
    clefairy: "Prankster",
    clefable: "Analytic",
    igglybuff: "Huge Power",
    jigglypuff: "Huge Power",
    wigglytuff: "Huge Power",
    togepi: "Pixilate",
    togetic: "Pixilate",
    togekiss: "Pixilate",
    natu: "Tinted Lens",
    xatu: "Sheer Force",
    mareep: "Electromorphosis",
    flaaffy: "Electromorphosis",
    ampharos: "Electromorphosis",
    hoppip: "Wind Rider",
    skiploom: "Wind Rider",
    jumpluff: "Fluffy",
    aipom: "Scrappy",
    ambipom: "Scrappy",
    sunkern: "Drought",
    sunflora: "Drought",
    yanma: "Technician",
    yanmega: "Sheer Force",
    wooper: "Water Veil",
    quagsire: "Comatose",
    murkrow: "Unnerve",
    honchkrow: "Intimidate",
    misdreavus: "Beads of Ruin",
    mismagius: "Beads of Ruin",
    unown: "Adaptability",
    girafarig: "Parental Bond",
    farigiraf: "Parental Bond",
    pineco: "Rough Skin",
    forretress: "Iron Barbs",
    dunsparce: "Unaware",
    dudunsparce_two_segment: "Unaware", // <= WITHOUT PASSIVE
    dudunsparce_three_segment: "Unaware", // <= WITHOUT PASSIVE
    gligar: "Poison Touch",
    gliscor: "Toxic Boost",
    snubbull: "Pixilate",
    granbull: "Pixilate",
    qwilfish: "Toxic Debris",
    shuckle: "Harvest",
    heracross: "Technician",
    sneasel: "Tough Claws",
    weavile: "Tough Claws",
    teddiursa: "Run Away",
    ursaring: "Thick Fat",
    ursaluna: "Thick Fat",
    slugma: "Drought",
    magcargo: "Desolate Land",
    swinub: "Unaware",
    piloswine: "Unaware",
    mamoswine: "Slush Rush",
    corsola: "Storm Drain",
    remoraid: "Simple",
    octillery: "Simple",
    delibird: "Huge Power",
    skarmory: "Stamina",
    houndour: "Ball Fetch",
    houndoom: "Lightning Rod",
    phanpy: "Sturdy",
    donphan: "Speed Boost",
    stantler: "Speed Boost",
    wyrdeer: "Speed Boost",
    smeargle: "Prankster",
    tyrogue: "Defiant",
    hitmonlee: "Sheer Force",
    hitmonchan: "Moxie",
    hitmontop: "Speed Boost",
    smoochum: "Psychic Surge",
    jynx: "Psychic Surge",
    elekid: "Sheer Force",
    electabuzz: "Sheer Force",
    electivire: "Sheer Force",
    magby: "Sheer Force",
    magmar: "Sheer Force",
    magmortar: "Sheer Force",
    miltank: "Stamina",
    raikou: "Beast Boost",
    entei: "Beast Boost",
    suicune: "Beast Boost",
    larvitar: "Solid Rock",
    pupitar: "Solid Rock",
    tyranitar: "Solid Rock",
    lugia: "Delta Stream",
    ho_oh: "Magic Guard",
    celebi: "Psychic Surge"
};