export const pokerogue_pokemonKalos_passives = {
  chespin: "Rough Skin",
  quilladin: "Dauntless Shield",
  chesnaught: "Dauntless Shield",
  fennekin: "Fluffy",
  braixen: "Psychic Surge",
  delphox: "Psychic Surge",
  froakie: "Stakeout",
  frogadier: "Stakeout",
  greninja: "Stakeout",
  bunnelby: "Inner Focus",
  diggersby: "Thick Fat",
  fletchling: "Flame Body",
  fletchinder: "Magic Guard",
  talonflame: "Magic Guard",
  scatterbug: "Run Away",
  spewpa: "Compound Eyes",
  vivillon: "Prankster",
  litleo: "Drought",
  pyroar: "Drought",
  flabebe: "Grassy Surge",
  floette: "Grassy Surge",
  florges: "Grassy Surge",
  skiddo: "Seed Sower",
  gogoat: "Seed Sower",
  pancham: "Technician",
  pangoro: "Fur Coat",
  furfrou: "Fluffy",
  espurr: "Prankster",
  meowstic: "Fur Coat",
  honedge: "Sharpness",
  doublade: "Sharpness",
  aegislash: "Sharpness",
  spritzee: "Fur Coat",
  aromatisse: "Fur Coat",
  swirlix: "Ripen",
  slurpuff: "Ripen",
  inkay: "Shadow Shield",
  malamar: "Shadow Shield",
  binacle: "Sap Sipper",
  barbaracle: "Sap Sipper",
  skrelp: "Water Bubble",
  dragalge: "Dragons Maw",
  clauncher: "Protean",
  clawitzer: "Protean",
  helioptile: "Protean",
  heliolisk: "Protean",
  tyrunt: "Sheer Force",
  tyrantrum: "Sheer Force",
  amaura: "Ice Scales",
  aurorus: "Ice Scales",
  hawlucha: "Moxie",
  dedenne: "Pixilate",
  carbink: "Solid Rock",
  goomy: "Regenerator",
  sliggoo: "Poison Heal",
  goodra: "Poison Heal",
  hisui_sliggoo: "Regenerator",
  hisui_goodra: "Regenerator",
  klefki: "Levitate",
  phantump: "Shadow Tag",
  trevenant: "Shadow Tag",
  pumpkaboo: "Illuminate",
  gourgeist: "Illuminate",
  bergmite: "Ice Scales",
  avalugg: "Ice Scales",
  hisui_avalugg: "Ice Scales",
  noibat: "Cheek Pouch",
  noivern: "Punk Rock",
  xerneas: "Harvest",
  yveltal: "Soul Heart",
  zygarde: "Unnerve",
  diancie: "Solid Rock",
  hoopa: "Opportunist",
  volcanion: "Neutralizing Gas",
  eternal_floette: "Magic Guard"
}
