export const pokerogue_pokemonPassives_Kanto = {
  bulbasaur: "Grassy Surge",
  ivysaur: "Grassy Surge",
  venusaur: "Grassy Surge",
  mega_venusaur: "Seed Sower",
  gigantamax_venusaur: "Flower Veil",
  charmander: "Sheer Force",
  charmeleon: "Beast Boost",
  charizard: "Beast Boost",
  mega_charizard_x: "Levitate",
  mega_charizard_y: "Turboblaze",
  gigantamax_charizard: "Unnerve",
  squirtle: "Bulletproof",
  wartortle: "Bulletproof",
  blastoise: "Bulletproof",
  mega_blastoise: "Bulletproof",
  gigantamax_blastoise: "Bulletproof",
  caterpie: "Gluttony", 
  metapod: "Sturdy",
  butterfree: "Magician",
  weedle: "Poison Touch",
  kakuna: "Sturdy",
  beedrill: "Adaptability",
  mega_beedrill: "Tinted Lens",
  pidgey: "Sheer Force",
  pidgeotto: "Sheer Force",
  pidgeot: "Sheer Force",
  mega_pidgeot: "Sheer Force",
  rattata: "Strong Jaw",
  raticate: "Strong Jaw",
  spearow: "Speed Boost",
  fearow: "Speed Boost",
  ekans: "Regenerator",
  arbok: "Regenerator",
  sandshrew: "Tough Claws",
  sandslash: "Tough Claws",
  nidoran_f: "Toxic Debris",
  nidorina: "Toxic Debris",
  nidoqueen: "Toxic Debris",
  nidoran_m: "Guts",
  nidorino: "Guts",
  nidoking: "Guts",
  vulpix: "Fur Coat",
  ninetales: "Fur Coat",
  zubat: "Intimidate",
  golbat: "Intimidate",
  crobat: "Intimidate",
  oddish: "Triage",
  gloom: "Triage",
  vileplume: "Triage",
  bellossom: "Triage",
  paras: "Triage",
  parasect: "Triage",
  venonat: "Fluffy",
  venomoth: "Simple",
  diglett: "Sturdy",
  dugtrio: "Sturdy",
  meowth: "Tough Claws",
  gigantamax_meowth: "Tough Claws",
  persian: "Tough Claws",
  psyduck: "Simple",
  golduck: "Simple",
  mankey: "Iron Fist",
  primeape: "Iron Fist",
  annihilape: "Iron Fist",
  growlithe: "Fluffy",
  arcanine: "Fluffy",
  poliwag: "No Guard",
  poliwhirl: "No Guard",
  poliwrath: "No Guard",
  politoed: "No Guard",
  abra: "Comatose",
  kadabra: "Magician",
  alakazam: "Magician",
  mega_alakazam: "Magician",
  machop: "Quick Feet",
  machoke: "Quick Feet",
  machamp: "Quick Feet",
  gigantamax_machamp: "Quick Feet",
  bellsprout: "Flower Gift",
  weepinbell: "Flower Gift",
  victreebel: "Flower Gift",
  tentacool: "Toxic Chain",
  tentacruel: "Toxic Chain",
  geodude: "Dry Skin",
  graveler: "Dry Skin",
  golem: "Dry Skin",
  ponyta: "Magic Guard",
  rapidash: "Magic Guard",
  slowpoke: "Unaware",
  slowbro: "Unaware",
  mega_slowbro: "Regenerator",
  slowking: "Unaware",
  magnemite: "Levitate",
  magneton: "Levitate",
  magnezone: "Levitate",
  farfetchd: "Sniper",
  doduo: "Parental Bond",
  dodrio: "Parental Bond",
  seel: "Water Bubble",
  dewgong: "Water Bubble",
  grimer: "Water Absorb",
  muk: "Water Absorb",
  shellder: "Sturdy",
  cloyster: "Ice Scales",
  gastly: "Prankster",
  haunter: "Prankster",
  gengar: "Levitate",
  mega_gengar: "Unnerve",
  gigantamax_gengar: "Regenerator",
  onix: "Rocky Payload",
  steelix: "Rocky Payload",
  mega_steelix: "Sand Spit",
  drowzee: "Magician",
  hypno: "Magician",
  krabby: "Unburden",
  kingler: "Unburden",
  gigantamax_kingler: "Unburden",
  voltorb: "Transistor",
  electrode: "Transistor",
  exeggcute: "Ripen",
  exeggutor: "Ripen",
  alola_exeggutor: "Unburden",
  cubone: "Parental Bond",
  marowak: "Parental Bond",
  alola_marowak: "Parental Bond",
  lickitung: "Cheek Pouch",
  lickilicky: "Cheek Pouch",
  koffing: "White Smoke",
  weezing: "Parental Bond",
  galar_weezing: "Parental Bond",
  rhyhorn: "Solid Rock",
  rhydon: "Solid Rock",
  rhyperior: "Filter",
  tangela: "Seed Sower",
  tangrowth: "Seed Sower",
  kangaskhan: "Technician",
  // MEGA KANGASKHAN
  horsea: "Dragons Maw",
  seadra: "Dragons Maw",
  kingdra: "Multiscale",
  goldeen: "Multiscale",
  seaking: "Multiscale",
  staryu: "Regenerator",
  starmie: "Regenerator",
  scyther: "Tinted Lens",
  scizor: "Tough Claws",
  // MEGA SCIZOR
  kleavor: "Weak Armor",
  pinsir: "Tinted Lens",
  // MEGA PINSIR
  tauros: "Stamina",
  magikarp: "Multiscale",
  gyarados: "Multiscale",
  // MEGA GYARADOS
  lapras: "Filter",
  ditto: "Adaptability",
  eevee: "Pickup",
  vaporeon: "Regenerator",
  jolteon: "Transistor",
  flareon: "Fur Coat",
  espeon: "Magician",
  umbreon: "Toxic Chain",
  leafeon: "Grassy Surge",
  glaceon: "Snow Warning",
  sylveon: "Competitive",
  porygon: "Transistor",
  porygon2: "Transistor",
  porygon_z: "Protean",
  omanyte: "Sturdy",
  omastar: "Sturdy",
  kabuto: "Tough Claws",
  kabutops: "Tough Claws",
  aerodactyl: "Intimidate",
  // MEGA AERODACTYL
  articuno: "Snow Warning",
  zapdos: "Drizzle",
  moltres: "Drought",
  dratini: "Multiscale",
  dragonair: "Multiscale",
  dragonite: "Aerilate",
  mewtwo: "Neuroforce",
  // MEGA MEWTWO X
  // MEGA MEWTWO Y
  mew: "Protean"
};