export const pokerogue_pokemonGalar_passives = {
  grookey: "Pickpocket",
  thwackey: "Pickpocket",
  rillaboom: "Grass Pelt",
  scorbunny: "Opportunist",
  raboot: "Opportunist",
  cinderace: "Opportunist",
  sobble: "Super Luck",
  drizzile: "Super Luck",
  inteleon: "Super Luck",
  skwovet: "Harvest",
  greedent: "Harvest",
  rookidee: "Gale Wings",
  corvisquire: "Gale Wings",
  corviknight: "Iron Barbs",
  blipbug: "Run Away",
  dottler: "Psychic Surge",
  orbeetle: "Psychic Surge",
  nickit: "Magician",
  thievul: "Magician",
  gossifleur: "Seed Sower",
  eldegoss: "Grassy Surge",
  wooloo: "Scrappy",
  dubwool: "Scrappy",
  chewtle: "Solid Rock",
  drednaw: "Solid Rock",
  yamper: "Pickup",
  boltund: "Sheer Force",
  rolycoly: "Solid Rock",
  carkol: "Solid Rock",
  coalossal: "Solid Rock",
  applin: "Sturdy",
  flapple: "No Guard",
  appletun: "Well Baked Body",
  dipplin: "Parental Bond",
  hydrapple: "Parental Bond",
  silicobra: "Sand Rush",
  sandaconda: "Sand Rush",
  cramorant: "Lightning Rod",
  arrokuda: "Speed Boost",
  barraskewda: "Intimidate",
  toxel: "Electric Surge",
  toxtricity: "Electric Surge",
  sizzlipede: "Hustle",
  centiskorch: "Hustle",
  clobbopus: "Water Bubble",
  grapploct: "Water Bubble",
  sinistea: "Shadow Shield",
  polteageist: "Shadow Shield",
  hatenna: "Fairy Aura",
  hattrem: "Fairy Aura",
  hatterene: "Fairy Aura",
  impidimp: "Intimidate",
  morgrem: "Intimidate",
  grimmsnarl: "Intimidate",
  milcery: "Regenerator",
  alcremie: "Regenerator",
  falinks: "Dauntless Shield",
  pincurchin: "Electromorphosis",
  snom: "Snow Warning",
  frosmoth: "Snow Warning",
  stonjourner: "Sturdy",
  eiscue: "Ice Scales",
  indeedee: "Hospitality",
  morpeko: "Moody",
  cufant: "Earth Eater",
  copperajah: "Earth Eater",
  dracozolt: "No Guard",
  arctozolt: "Water Absorb",
  dracovish: "Thermal Exchange",
  arctovish: "Strong Jaw",
  duraludon: "Filter",
  archaludon: "Transistor",
  dreepy: "Technician",
  drakloak: "Parental Bond",
  dragapult: "Parental Bond",
  zacian: "Unnerve",
  zamazenta: "Unnerve",
  eternatus: "Neutralizing Gas",
  kubfu: "Iron Fist",
  urshifu: "Iron Fist",
  zarude: "Tough Claws",
  regieleki: "Electric Surge",
  regidrago: "Multiscale",
  glastrier: "Filter",
  spectrier: "Dazzling",
  calyrex: "Harvest",
  enamorus: "Fairy Aura",
  meowth_galar: "Unburden",
  perrserker: "Unburden",
  ponyta_galar: "Chilling Neigh",
  rapidash_galar: "Chilling Neigh",
  slowpoke_galar: "Oblivious",
  slowbro_galar: "Neuroforce",
  slowking_galar: "Intimidate",
  farfetchd_galar: "Stakeout",
  sirfetchd: "Intrepid Sword",
  articuno_galar: "Serene Grace",
  zapdos_galar: "Tough Claws",
  moltres_galar: "Dark Aura",
  corsola_galar: "Shadow Shield",
  cursola: "Shadow Shield",
  zigzagoon_galar: "Poison Heal",
  linoone_galar: "Poison Heal",
  obstagoon: "Poison Heal",
  darumaka_galar: "Flash Fire",
  darmanitan_galar: "Flash Fire",
  yamask_galar: "Tablets Of Ruin",
  runerigus: "Tablets Of Ruin",
  stunfisk_galar: "Arena Trap",
  growlithe_hisui: "Reckless",
  arcanine_hisui: "Reckless",
  voltorb_hisui: "Magic Guard",
  electrode_hisui: "Magic Guard",
  qwilfish_hisui: "Merciless",
  overqwil: "Merciless",
  sneasel_hisui: "Scrappy",
  sneasler: "Scrappy",
  zorua_hisui: "Shadow Shield",
  zoroark_hisui: "Shadow Shield"
}
