export const pokerogue_pokemonAlola_passives = {
  rowlet: "Wind Rider",
  dartrix: "Wind Rider",
  decidueye: "Sniper",
  hisui_decidueye: "Sniper",
  litten: "Tough Claws",
  torracat: "Tough Claws",
  incineroar: "Tough Claws",
  popplio: "Punk Rock",
  brionne: "Punk Rock",
  primarina: "Punk Rock",
  pikipek: "Technician",
  trumbeak: "Technician",
  toucannon: "Technician",
  yungoos: "Tough Claws",
  gumshoos: "Tough Claws",
  grubbin: "Shield Dust",
  charjabug: "Power Spot",
  vikavolt: "Speed Boost",
  crabrawler: "Water Bubble",
  crabominable: "Water Bubble",
  oricorio: "Adaptability",
  cutiefly: "Pickup",
  ribombee: "Pickup",
  rockruff: "Pickup",
  lycanroc: "Sturdy",
  wishiwashi: "Regenerator",
  mareanie: "Toxic Debris",
  toxapex: "Toxic Debris",
  mudbray: "Sap Sipper",
  mudsdale: "Sap Sipper",
  dewpider: "Tinted Lens",
  araquanid: "Tinted Lens",
  fomantis: "Sharpness",
  lurantis: "Sharpness",
  morelull: "Triage",
  shiinotic: "Triage",
  salandit: "Pickup",
  salazzle: "Dragons Maw",
  stufful: "Scrappy",
  bewear: "Scrappy",
  bounsweet: "Simple",
  steenee: "Simple",
  tsareena: "Moxie",
  comfey: "Friend Guard",
  oranguru: "Power Spot",
  passimian: "Libero",
  wimpod: "Regenerator",
  golisopod: "Regenerator",
  sandygast: "Sand Spit",
  palossand: "Sand Spit",
  pyukumuku: "Purifying Salt",
  type_null: "Clear Body", // <= WITHOUT PASSIVE
  silvally: "Adaptability",
  minior: "Sturdy",
  komala: "Guts",
  turtonator: "Dauntless Shield",
  togedemaru: "Cheek Pouch",
  mimikyu: "Tough Claws",
  bruxish: "Multiscale",
  drampa: "Thick Fat",
  dhelmise: "Water Bubble",
  jangmo_o: "Dauntless Shield",
  hakamo_o: "Dauntless Shield",
  kommo_o: "Dauntless Shield",
  tapu_koko: "Dauntless Shield",
  tapu_lele: "Berserk",
  tapu_bulu: "Flower Veil",
  tapu_fini: "Fairy Aura",
  cosmog: "Power Spot",
  cosmoem: "Power Spot",
  solgaleo: "Beast Boost",
  lunala: "Beast Boost",
  nihilego: "Levitate",
  buzzwole: "Moxie",
  pheromosa: "Tinted Lens",
  xurkitree: "Transistor",
  celesteela: "Heatproof",
  kartana: "Technician",
  guzzlord: "Poison Heal",
  necrozma: "Beast Boost",
  magearna: "Steely Spirit",
  marshadow: "Iron Fist",
  poipole: "Levitate",
  naganadel: "Levitate",
  stakataka: "Solid Rock",
  blacephalon: "Magic Guard",
  zeraora: "Tough Claws",
  meltan: "Heatproof",
  melmetal: "Heatproof",
  alola_rattata: "Adaptability",
  alola_raticate: "Adaptability",
  alola_sandshrew: "Ice Scales",
  alola_sandslash: "Ice Scales",
  alola_vulpix: "Ice Body",
  alola_ninetales: "Ice Body",
  alola_diglett: "Sturdy",
  alola_dugtrio: "Sturdy",
  alola_meowth: "Dazzling",
  alola_persian: "Dazzling",
  alola_geodude: "Dry Skin",
  alola_graveler: "Dry Skin",
  alola_golem: "Dry Skin",
  alola_grimer: "Toxic Debris",
  alola_muk: "Toxic Debris"
}
