export const pokerogue_pokemonPaldea_passives = {
  sprigatito: "Pickup",
  floragato: "Magician",
  meowscarada: "Magician",
  fuecoco: "Gluttony",
  crocalor: "Punk Rock",
  skeledirge: "Punk Rock",
  quaxly: "Opportunist",
  quaxwell: "Opportunist",
  quaquaval: "Opportunist",
  lechonk: "Simple",
  oinkologne: "Simple",
  tarountula: "Honey Gather",
  spidops: "Honey Gather",
  nymble: "Technician",
  lokix: "Guts",
  pawmi: "Transistor",
  pawmo: "Transistor",
  pawmot: "Transistor",
  tandemaus: "Friend Guard",
  maushold: "Scrappy",
  fidough: "Water Absorb",
  dachsbun: "Water Absorb",
  smoliv: "Ripen",
  dolliv: "Ripen",
  arboliva: "Ripen",
  squawkabilly: "Moxie",
  nacli: "Solid Rock",
  naclstack: "Solid Rock",
  garganacl: "Solid Rock",
  charcadet: "Battle Armor",
  armarouge: "Prism Armor",
  ceruledge: "Prism Armor",
  tadbulb: "Levitate",
  bellibolt: "Stamina",
  wattrel: "Sheer Force",
  kilowattrel: "Sheer Force",
  maschiff: "Strong Jaw",
  mabosstiff: "Strong Jaw",
  shroodle: "Corrosion",
  grafaiai: "Corrosion",
  bramblin: "Wandering Spirit",
  brambleghast: "Shadow Shield",
  toedscool: "Run Away",
  toedscruel: "Prankster",
  klawf: "Water Absorb",
  capsakid: "Flower Gift",
  scovillain: "Parental Bond",
  rellor: "Prankster",
  rabsca: "Prankster",
  flittle: "Dazzling",
  espathra: "Dazzling",
  tinkatink: "Steelworker",
  tinkatuff: "Steelworker",
  tinkaton: "Steelworker",
  wiglett: "Sturdy",
  wugtrio: "Sturdy",
  bombirdier: "Unburden",
  finizen: "Friend Guard",
  palafin: "Emergency Exit",
  varoom: "Levitate",
  revavroom: "Levitate",
  cyclizar: "Protean",
  orthworm: "Regenerator",
  glimmet: "Sturdy",
  glimmora: "Tera Shell",
  greavard: "Unaware",
  houndstone: "Unaware",
  flamigo: "Moxie",
  cetoddle: "Refrigerate",
  cetitan: "Refrigerate",
  veluza: "Super Luck",
  dondozo: "Dragons Maw",
  tatsugiri: "Fluffy",
  great_tusk: "Intimidate",
  scream_tail: "Unaware",
  brute_bonnet: "Chlorophyll",
  flutter_mane: "Dazzling",
  slither_wing: "Scrappy",
  sandy_shocks: "Electric Surge",
  iron_treads: "Dauntless Shield",
  iron_bundle: "Snow Warning",
  iron_hands: "Iron Fist",
  iron_jugulis: "Lightning Rod",
  iron_moth: "Levitate",
  iron_thorns: "Sand Stream",
  frigibax: "Intimidate",
  arctibax: "Intimidate",
  baxcalibur: "Intimidate",
  gimmighoul: "Honey Gather",
  gholdengo: "Honey Gather",
  wo_chien: "Vessel Of Ruin",
  chien_pao: "Intimidate",
  ting_lu: "Stamina",
  chi_yu: "Berserk",
  roaring_moon: "Intimidate",
  iron_valiant: "Neuroforce",
  koraidon: "Thermal Exchange",
  miraidon: "Compound Eyes",
  walking_wake: "Beast Boost",
  iron_leaves: "Sharpness",
  poltchageist: "Triage",
  sinistcha: "Triage",
  okidogi: "Dark Aura",
  munkidori: "Magician",
  fezandipiti: "Pixilate",
  ogerpon: "Opportunist",
  gouging_fire: "Beast Boost",
  raging_bolt: "Beast Boost",
  iron_boulder: "Sharpness",
  iron_crown: "Sharpness",
  terapagos: "Shield Dust",
  pecharunt: "Toxic Chain",
  paldea_tauros: "Stamina",
  paldea_wooper: "Poison Touch",
  clodsire: "Thick Fat",
  bloodmoon_ursaluna: "Berserk"
}
