export const pokerogue_pokemonGalar_passives = {
  grookey: "Pickpocket",
  thwackey: "Pickpocket",
  rillaboom: "Grass Pelt",
  scorbunny: "Opportunist",
  raboot: "Opportunist",
  cinderace: "Opportunist",
  sobble: "Super Luck",
  drizzile: "Super Luck",
  inteleon: "Super Luck",
  skwovet: "Harvest",
  greedent: "Harvest",
  rookidee: "Gale Wings",
  corvisquire: "Gale Wings",
  corviknight: "Iron Barbs",
  blipbug: "Run Away",
  dottler: "Psychic Surge",
  orbeetle: "Psychic Surge",
  nickit: "Magician",
  thievul: "Magician",
  gossifleur: "Seed Sower",
  eldegoss: "Grassy Surge",
  wooloo: "Scrappy",
  dubwool: "Scrappy",
  chewtle: "Solid Rock",
  drednaw: "Solid Rock",
  yamper: "Pickup",
  boltund: "Sheer Force",
  rolycoly: "Solid Rock",
  carkol: "Solid Rock",
  coalossal: "Solid Rock",
  applin: "Sturdy",
  flapple: "No Guard",
  appletun: "Well Baked Body",
  dipplin: "Parental Bond",
  hydrapple: "Parental Bond",
  silicobra: "Sand Rush",
  sandaconda: "Sand Rush",
  cramorant: "Lightning Rod",
  arrokuda: "Speed Boost",
  barraskewda: "Intimidate",
  toxel: "Electric Surge",
  toxtricity: "Electric Surge",
  sizzlipede: "Hustle",
  centiskorch: "Hustle",
  clobbopus: "Water Bubble",
  grapploct: "Water Bubble",
  sinistea: "Shadow Shield",
  polteageist: "Shadow Shield",
  hatenna: "Fairy Aura",
  hattrem: "Fairy Aura",
  hatterene: "Fairy Aura",
  impidimp: "Intimidate",
  morgrem: "Intimidate",
  grimmsnarl: "Intimidate",
  milcery: "Regenerator",
  alcremie: "Regenerator",
  falinks: "Dauntless Shield",
  pincurchin: "Electromorphosis",
  snom: "Snow Warning",
  frosmoth: "Snow Warning",
  stonjourner: "Sturdy",
  eiscue: "Ice Scales",
  indeedee: "Hospitality",
  morpeko: "Moody",
  cufant: "Earth Eater",
  copperajah: "Earth Eater",
  dracozolt: "No Guard",
  arctozolt: "Water Absorb",
  dracovish: "Thermal Exchange",
  arctovish: "Strong Jaw",
  duraludon: "Filter",
  archaludon: "Transistor",
  dreepy: "Technician",
  drakloak: "Parental Bond",
  dragapult: "Parental Bond",
  zacian: "Unnerve",
  zamazenta: "Unnerve",
  eternatus: "Neutralizing Gas",
  kubfu: "Iron Fist",
  urshifu: "Iron Fist",
  zarude: "Tough Claws",
  regieleki: "Electric Surge",
  regidrago: "Multiscale",
  glastrier: "Filter",
  spectrier: "Dazzling",
  calyrex: "Harvest",
  enamorus: "Fairy Aura",
  galar_meowth: "Unburden",
  perrserker: "Unburden",
  galar_ponyta: "Chilling Neigh",
  galar_rapidash: "Chilling Neigh",
  galar_slowpoke: "Oblivious",
  galar_slowbro: "Neuroforce",
  galar_slowking: "Intimidate",
  galar_farfetchd: "Stakeout",
  sirfetchd: "Intrepid Sword",
  galar_articuno: "Serene Grace",
  galar_zapdos: "Tough Claws",
  galar_moltres: "Dark Aura",
  galar_corsola: "Shadow Shield",
  cursola: "Shadow Shield",
  galar_zigzagoon: "Poison Heal",
  galar_linoone: "Poison Heal",
  obstagoon: "Poison Heal",
  galar_darumaka: "Flash Fire",
  galar_darmanitan: "Flash Fire",
  galar_yamask: "Tablets Of Ruin",
  runerigus: "Tablets Of Ruin",
  galar_stunfisk: "Arena Trap",
  hisui_growlithe: "Reckless",
  hisui_arcanine: "Reckless",
  hisui_voltorb: "Magic Guard",
  hisui_electrode: "Magic Guard",
  hisui_qwilfish: "Merciless",
  overqwil: "Merciless",
  hisui_sneasel: "Scrappy",
  sneasler: "Scrappy",
  hisui_zorua: "Shadow Shield",
  hisui_zoroark: "Shadow Shield"
}
