export const pokerogue_pokemonUnova_passives = {
  victini: "Serene Grace",
  snivy: "Multiscale",
  servine: "Multiscale",
  serperior: "Multiscale",
  tepig: "Gluttony",
  pignite: "Rock Head",
  emboar: "Rock Head",
  oshawott: "Mold Breaker",
  dewott: "Mold Breaker",
  samurott: "Lightning Rod",
  samurott_hisui: "Mold Breaker",
  patrat: "No Guard",
  watchog: "No Guard",
  lillipup: "Ball Fetch",
  herdier: "Fur Coat",
  stoutland: "Fur Coat",
  purrloin: "Pickup",
  liepard: "Pickup",
  pansage: "Well Baked Body",
  simisage: "Well Baked Body",
  pansear: "Water Absorb",
  simisear: "Water Absorb",
  panpour: "Sap Sipper",
  simipour: "Sap Sipper",
  munna: "Neutralizing Gas",
  musharna: "Neutralizing Gas",
  pidove: "Sniper",
  tranquill: "Sniper",
  unfezant: "Sniper",
  blitzle: "Electric Surge",
  zebstrika: "Electric Surge",
  roggenrola: "Solid Rock",
  boldore: "Solid Rock",
  gigalith: "Solid Rock",
  woobat: "Opportunist",
  swoobat: "Opportunist",
  drilbur: "Sturdy",
  excadrill: "Sturdy",
  audino: "Friend Guard",
  timburr: "Rocky Payload",
  gurdurr: "Rocky Payload",
  conkeldurr: "Rocky Payload",
  tympole: "Poison Heal",
  palpitoad: "Poison Heal",
  seismitoad: "Poison Heal",
  throh: "Stamina",
  sawk: "Scrappy",
  sewaddle: "Shield Dust",
  swadloon: "Shield Dust",
  leavanny: "Sharpness",
  venipede: "Stamina",
  whirlipede: "Stamina",
  scolipede: "Stamina",
  cottonee: "Fluffy",
  whimsicott: "Fluffy",
  petilil: "Flower Veil",
  lilligant: "Grassy Surge",
  lilligant_hisui: "Flower Veil",
  basculin: "Rock Head",
  basculegion: "Supreme Overlord",
  sandile: "Tough Claws",
  krokorok: "Tough Claws",
  krookodile: "Tough Claws",
  darumaka: "Gorilla Tactics",
  darmanitan: "Gorilla Tactics",
  darmanitan_zen: "Psychic Surge",
  maractus: "Well Baked Body",
  dwebble: "Rocky Payload",
  crustle: "Rocky Payload",
  scraggy: "Unburden",
  scrafty: "Unburden",
  sigilyph: "Flare Boost",
  yamask: "Purifying Salt",
  cofagrigus: "Purifying Salt",
  tirtouga: "Water Absorb",
  carracosta: "Water Absorb",
  archen: "Multiscale",
  archeops: "Multiscale",
  trubbish: "Neutralizing Gas",
  garbodor: "Neutralizing Gas",
  zorua: "Adaptability",
  zoroark: "Adaptability",
  minccino: "Fur Coat",
  cinccino: "Fur Coat",
  gothita: "Unnerve",
  gothorita: "Unnerve",
  gothitelle: "Unnerve",
  solosis: "Psychic Surge",
  duosion: "Psychic Surge",
  reuniclus: "Psychic Surge",
  ducklett: "Drizzle",
  swanna: "Drizzle",
  vanillite: "Refrigerate",
  vanillish: "Refrigerate",
  vanilluxe: "Slush Rush",
  deerling: "Flower Veil",
  sawsbuck: "Flower Veil",
  emolga: "Serene Grace",
  karrablast: "Quick Draw",
  escavalier: "Quick Draw",
  foongus: "Mycelium Might",
  amoonguss: "Thick Fat",
  frillish: "Poison Heal",
  jellicent: "Poison Heal",
  alomomola: "Multiscale",
  joltik: "Transistor",
  galvantula: "Transistor",
  ferroseed: "Rough Skin",
  ferrothorn: "Rough Skin",
  klink: "Steely Spirit",
  klang: "Steely Spirit",
  klinklang: "Steely Spirit",
  tynamo: "Poison Heal",
  eelektrik: "Poison Heal",
  eelektross: "Poison Heal",
  elgyem: "Beads Of Ruin",
  beheeyem: "Beads Of Ruin",
  litwick: "Shadow Tag",
  lampent: "Shadow Tag",
  chandelure: "Shadow Tag",
  axew: "Own Tempo",
  fraxure: "Own Tempo",
  haxorus: "Own Tempo",
  cubchoo: "Fur Coat",
  beartic: "Fur Coat",
  cryogonal: "Snow Warning",
  shelmet: "Stamina",
  accelgor: "Protean",
  stunfisk: "Storm Drain",
  mienfoo: "No Guard",
  mienshao: "No Guard",
  druddigon: "Intimidate",
  golett: "Shadow Shield",
  golurk: "Shadow Shield",
  pawniard: "Sword Of Ruin",
  bisharp: "Sword Of Ruin",
  kingambit: "Sword Of Ruin",
  bouffalant: "Rock Head",
  rufflet: "Speed Boost",
  braviary: "Speed Boost",
  braviary_hisui: "Speed Boost",
  vullaby: "Thick Fat",
  mandibuzz: "Thick Fat",
  heatmor: "Contrary",
  durant: "Compound Eyes",
  deino: "No Guard",
  zweilous: "No Guard",
  hydreigon: "Parental Bond",
  larvesta: "Flash Fire",
  volcarona: "Flash Fire",
  cobalion: "Intrepid Sword",
  terrakion: "Rocky Payload",
  virizion: "Sharpness",
  tornadus: "Drizzle",
  thundurus: "Drizzle",
  reshiram: "Orichalcum Pulse",
  zekrom: "Hadron Engine",
  landorus: "Storm Drain",
  kyurem: "Snow Warning",
  keldeo: "Grim Neigh",
  meloetta: "Punk Rock",
  meloetta_pirouette: "Scrappy",
  genesect: "Protean"
}
