export const pokerogue_pokemonHoenn_passives = {
  treecko: "Tinted Lens",
  grovyle: "Tinted Lens",
  sceptile: "Tinted Lens",
  torchic: "Defiant",
  combusken: "Defiant",
  blaziken: "Defiant",
  mudkip: "Regenerator",
  marshtomp: "Regenerator",
  swampert: "Regenerator",
  poochyena: "Tough Claws",
  mightyena: "Tough Claws",
  zigzagoon: "Run Away",
  linoone: "Run Away",
  wurmple: "Gluttony",
  silcoon: "Sturdy",
  beautifly: "Simple",
  cascoon: "Sturdy",
  dustox: "Simple",
  lotad: "Drizzle",
  lombre: "Drizzle",
  ludicolo: "Drizzle",
  seedot: "Sturdy",
  nuzleaf: "Sharpness",
  shiftry: "Sharpness",
  taillow: "Aerilate",
  swellow: "Aerilate",
  wingull: "Water Absorb",
  pelipper: "Swift Swim",
  ralts: "Neuroforce",
  kirlia: "Neuroforce",
  gardevoir: "Neuroforce",
  gallade: "Neuroforce",
  surskit: "Water Bubble",
  masquerain: "Water Bubble",
  shroomish: "Guts",
  breloom: "Guts",
  slakoth: "Comatose",
  vigoroth: "Tough Claws",
  slaking: "Comatose",
  nincada: "Technician",
  ninjask: "Technician",
  shedinja: "Magic Guard",
  whismur: "Punk Rock",
  loudred: "Punk Rock",
  exploud: "Punk Rock",
  makuhita: "Stamina",
  hariyama: "Stamina",
  azurill: "Misty Surge",
  marill: "Misty Surge",
  azumarill: "Misty Surge",
  nosepass: "Solid Rock",
  probopass: "Levitate",
  skitty: "Scrappy",
  delcatty: "Scrappy",
  sableye: "Unnerve",
  mawile: "Adaptability",
  aron: "Earth Eater",
  lairon: "Earth Eater",
  aggron: "Earth Eater",
  meditite: "Minds Eye",
  medicham: "Minds Eye",
  electrike: "Ball Fetch",
  manectric: "Flash Fire",
  plusle: "Power Spot",
  minun: "Power Spot",
  volbeat: "Honey Gather",
  illumise: "Honey Gather",
  gulpin: "Earth Eater",
  swalot: "Earth Eater",
  carvanha: "Sheer Force",
  sharpedo: "Sheer Force",
  wailmer: "Levitate",
  wailord: "Levitate",
  numel: "Solid Rock",
  camerupt: "Fur Coat",
  torkoal: "Analytic",
  spoink: "Psychic Surge",
  grumpig: "Psychic Surge",
  spinda: "Simple",
  trapinch: "Adaptability",
  vibrava: "Adaptability",
  flygon: "Adaptability",
  cacnea: "Sand Rush",
  cacturne: "Sand Rush",
  swablu: "Fluffy",
  altaria: "Fluffy",
  zangoose: "Poison Heal",
  seviper: "Multiscale",
  lunatone: "Shadow Shield",
  solrock: "Drought",
  barboach: "Simple",
  whiscash: "Simple",
  corphish: "Tough Claws",
  crawdaunt: "Tough Claws",
  baltoy: "Well Baked Body",
  claydol: "Well Baked Body",
  lileep: "Seed Sower",
  cradily: "Seed Sower",
  anorith: "Water Absorb",
  armaldo: "Water Absorb",
  feebas: "Multiscale",
  milotic: "Magic Guard",
  castform: "Adaptability",
  castform_sunny: "Adaptability",
  castform_rainy: "Adaptability",
  castform_snowy: "Adaptability",
  kecleon: "Adaptability",
  shuppet: "Shadow Shield",
  banette: "Shadow Shield",
  duskull: "Unnerve",
  dusclops: "Unnerve",
  dusknoir: "Levitate",
  tropius: "Ripen",
  absol: "Sharpness",
  wynaut: "Sturdy",
  wobuffet: "Sturdy",
  snorunt: "Snow Warning",
  glalie: "Snow Warning",
  froslass: "Snow Warning",
  spheal: "Unaware",
  sealeo: "Unaware",
  walrein: "Unaware",
  clamperl: "Overcoat",
  gorebyss: "Arena Trap",
  huntail: "Arena Trap",
  relicanth: "Primordial Sea",
  luvdisc: "Multiscale",
  bagon: "Intimidate",
  shelgon: "Anger Shell",
  salamence: "Gale Wings",
  beldum: "Levitate",
  metang: "Levitate",
  metagross: "Levitate",
  regirock: "Sand Stream",
  regice: "Snow Warning",
  registeel: "Steely Spirit",
  latias: "Prism Armor",
  latios: "Neuroforce",
  kyogre: "Mold Breaker",
  groudon: "Mold Breaker",
  rayquaza: "Unnerve",
  jirachi: "Purifying Salt",
  deoxys: "Protean"
};