export const pokerogue_pokemonPassives_Kanto = {
  [SpeciesId.BULBASAUR]: { 0: AbilityId.GRASSY_SURGE },
  [SpeciesId.IVYSAUR]: { 0: AbilityId.GRASSY_SURGE },
  [SpeciesId.VENUSAUR]: { 0: AbilityId.GRASSY_SURGE, 1: AbilityId.SEED_SOWER, 2: AbilityId.FLOWER_VEIL },
  [SpeciesId.CHARMANDER]: { 0: AbilityId.SHEER_FORCE },
  [SpeciesId.CHARMELEON]: { 0: AbilityId.BEAST_BOOST },
  [SpeciesId.CHARIZARD]: { 0: AbilityId.BEAST_BOOST, 1: AbilityId.LEVITATE, 2: AbilityId.TURBOBLAZE, 3: AbilityId.UNNERVE },
  [SpeciesId.SQUIRTLE]: { 0: AbilityId.BULLETPROOF },
  [SpeciesId.WARTORTLE]: { 0: AbilityId.BULLETPROOF },
  [SpeciesId.BLASTOISE]: { 0: AbilityId.BULLETPROOF, 1: AbilityId.BULLETPROOF, 2: AbilityId.BULLETPROOF },
  [SpeciesId.CATERPIE]: { 0: AbilityId.GLUTTONY },
  [SpeciesId.METAPOD]: { 0: AbilityId.STURDY },
  [SpeciesId.BUTTERFREE]: { 0: AbilityId.MAGICIAN, 1: AbilityId.MAGICIAN },
  [SpeciesId.WEEDLE]: { 0: AbilityId.POISON_TOUCH },
  [SpeciesId.KAKUNA]: { 0: AbilityId.STURDY },
  [SpeciesId.BEEDRILL]: { 0: AbilityId.ADAPTABILITY, 1: AbilityId.TINTED_LENS },
  [SpeciesId.PIDGEY]: { 0: AbilityId.SHEER_FORCE },
  [SpeciesId.PIDGEOTTO]: { 0: AbilityId.SHEER_FORCE },
  [SpeciesId.PIDGEOT]: { 0: AbilityId.SHEER_FORCE, 1: AbilityId.SHEER_FORCE },
  [SpeciesId.RATTATA]: { 0: AbilityId.STRONG_JAW },
  [SpeciesId.RATICATE]: { 0: AbilityId.STRONG_JAW },
  [SpeciesId.SPEAROW]: { 0: AbilityId.SPEED_BOOST },
  [SpeciesId.FEAROW]: { 0: AbilityId.SPEED_BOOST },
  [SpeciesId.EKANS]: { 0: AbilityId.REGENERATOR },
  [SpeciesId.ARBOK]: { 0: AbilityId.REGENERATOR },
  [SpeciesId.SANDSHREW]: { 0: AbilityId.TOUGH_CLAWS },
  [SpeciesId.SANDSLASH]: { 0: AbilityId.TOUGH_CLAWS },
  [SpeciesId.NIDORAN_F]: { 0: AbilityId.TOXIC_DEBRIS },
  [SpeciesId.NIDORINA]: { 0: AbilityId.TOXIC_DEBRIS },
  [SpeciesId.NIDOQUEEN]: { 0: AbilityId.TOXIC_DEBRIS },
  [SpeciesId.NIDORAN_M]: { 0: AbilityId.GUTS },
  [SpeciesId.NIDORINO]: { 0: AbilityId.GUTS },
  [SpeciesId.NIDOKING]: { 0: AbilityId.GUTS },
  [SpeciesId.VULPIX]: { 0: AbilityId.FUR_COAT },
  [SpeciesId.NINETALES]: { 0: AbilityId.FUR_COAT },
  [SpeciesId.ZUBAT]: { 0: AbilityId.INTIMIDATE },
  [SpeciesId.GOLBAT]: { 0: AbilityId.INTIMIDATE },
  [SpeciesId.CROBAT]: { 0: AbilityId.INTIMIDATE },
  [SpeciesId.ODDISH]: { 0: AbilityId.TRIAGE },
  [SpeciesId.GLOOM]: { 0: AbilityId.TRIAGE },
  [SpeciesId.VILEPLUME]: { 0: AbilityId.TRIAGE },
  [SpeciesId.BELLOSSOM]: { 0: AbilityId.TRIAGE },
  [SpeciesId.PARAS]: { 0: AbilityId.TRIAGE },
  [SpeciesId.PARASECT]: { 0: AbilityId.TRIAGE },
  [SpeciesId.VENONAT]: { 0: AbilityId.FLUFFY },
  [SpeciesId.VENOMOTH]: { 0: AbilityId.SIMPLE },
  [SpeciesId.DIGLETT]: { 0: AbilityId.STURDY },
  [SpeciesId.DUGTRIO]: { 0: AbilityId.STURDY },
  [SpeciesId.MEOWTH]: { 0: AbilityId.TOUGH_CLAWS, 1: AbilityId.TOUGH_CLAWS },
  [SpeciesId.PERSIAN]: { 0: AbilityId.TOUGH_CLAWS },
  [SpeciesId.PSYDUCK]: { 0: AbilityId.SIMPLE },
  [SpeciesId.GOLDUCK]: { 0: AbilityId.SIMPLE },
  [SpeciesId.MANKEY]: { 0: AbilityId.IRON_FIST },
  [SpeciesId.PRIMEAPE]: { 0: AbilityId.IRON_FIST },
  [SpeciesId.ANNIHILAPE]: { 0: AbilityId.IRON_FIST },
  [SpeciesId.GROWLITHE]: { 0: AbilityId.FLUFFY },
  [SpeciesId.ARCANINE]: { 0: AbilityId.FLUFFY },
  [SpeciesId.POLIWAG]: { 0: AbilityId.NO_GUARD },
  [SpeciesId.POLIWHIRL]: { 0: AbilityId.NO_GUARD },
  [SpeciesId.POLIWRATH]: { 0: AbilityId.NO_GUARD },
  [SpeciesId.POLITOED]: { 0: AbilityId.NO_GUARD },
  [SpeciesId.ABRA]: { 0: AbilityId.COMATOSE },
  [SpeciesId.KADABRA]: { 0: AbilityId.MAGICIAN },
  [SpeciesId.ALAKAZAM]: { 0: AbilityId.MAGICIAN, 1: AbilityId.MAGICIAN },
  [SpeciesId.MACHOP]: { 0: AbilityId.QUICK_FEET },
  [SpeciesId.MACHOKE]: { 0: AbilityId.QUICK_FEET },
  [SpeciesId.MACHAMP]: { 0: AbilityId.QUICK_FEET, 1: AbilityId.QUICK_FEET },
  [SpeciesId.BELLSPROUT]: { 0: AbilityId.FLOWER_GIFT },
  [SpeciesId.WEEPINBELL]: { 0: AbilityId.FLOWER_GIFT },
  [SpeciesId.VICTREEBEL]: { 0: AbilityId.FLOWER_GIFT },
  [SpeciesId.TENTACOOL]: { 0: AbilityId.TOXIC_CHAIN },
  [SpeciesId.TENTACRUEL]: { 0: AbilityId.TOXIC_CHAIN },
  [SpeciesId.GEODUDE]: { 0: AbilityId.DRY_SKIN },
  [SpeciesId.GRAVELER]: { 0: AbilityId.DRY_SKIN },
  [SpeciesId.GOLEM]: { 0: AbilityId.DRY_SKIN },
  [SpeciesId.PONYTA]: { 0: AbilityId.MAGIC_GUARD },
  [SpeciesId.RAPIDASH]: { 0: AbilityId.MAGIC_GUARD },
  [SpeciesId.SLOWPOKE]: { 0: AbilityId.UNAWARE },
  [SpeciesId.SLOWBRO]: { 0: AbilityId.UNAWARE, 1: AbilityId.REGENERATOR },
  [SpeciesId.SLOWKING]: { 0: AbilityId.UNAWARE },
  [SpeciesId.MAGNEMITE]: { 0: AbilityId.LEVITATE },
  [SpeciesId.MAGNETON]: { 0: AbilityId.LEVITATE },
  [SpeciesId.MAGNEZONE]: { 0: AbilityId.LEVITATE },
  [SpeciesId.FARFETCHD]: { 0: AbilityId.SNIPER },
  [SpeciesId.DODUO]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.DODRIO]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.SEEL]: { 0: AbilityId.WATER_BUBBLE },
  [SpeciesId.DEWGONG]: { 0: AbilityId.WATER_BUBBLE },
  [SpeciesId.GRIMER]: { 0: AbilityId.WATER_ABSORB },
  [SpeciesId.MUK]: { 0: AbilityId.WATER_ABSORB },
  [SpeciesId.SHELLDER]: { 0: AbilityId.STURDY },
  [SpeciesId.CLOYSTER]: { 0: AbilityId.ICE_SCALES },
  [SpeciesId.GASTLY]: { 0: AbilityId.PRANKSTER },
  [SpeciesId.HAUNTER]: { 0: AbilityId.PRANKSTER },
  [SpeciesId.GENGAR]: { 0: AbilityId.LEVITATE, 1: AbilityId.UNNERVE, 2: AbilityId.REGENERATOR },
  [SpeciesId.ONIX]: { 0: AbilityId.ROCKY_PAYLOAD },
  [SpeciesId.STEELIX]: { 0: AbilityId.ROCKY_PAYLOAD, 1: AbilityId.SAND_SPIT },
  [SpeciesId.DROWZEE]: { 0: AbilityId.MAGICIAN },
  [SpeciesId.HYPNO]: { 0: AbilityId.MAGICIAN },
  [SpeciesId.KRABBY]: { 0: AbilityId.UNBURDEN },
  [SpeciesId.KINGLER]: { 0: AbilityId.UNBURDEN, 1: AbilityId.UNBURDEN },
  [SpeciesId.VOLTORB]: { 0: AbilityId.TRANSISTOR },
  [SpeciesId.ELECTRODE]: { 0: AbilityId.TRANSISTOR },
  [SpeciesId.EXEGGCUTE]: { 0: AbilityId.RIPEN },
  [SpeciesId.EXEGGUTOR]: { 0: AbilityId.RIPEN },
  [SpeciesId.ALOLA_EXEGGUTOR]: { 0: AbilityId.UNBURDEN },
  [SpeciesId.CUBONE]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.MAROWAK]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.ALOLA_MAROWAK]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.LICKITUNG]: { 0: AbilityId.CHEEK_POUCH },
  [SpeciesId.LICKILICKY]: { 0: AbilityId.CHEEK_POUCH },
  [SpeciesId.KOFFING]: { 0: AbilityId.WHITE_SMOKE },
  [SpeciesId.WEEZING]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.GALAR_WEEZING]: { 0: AbilityId.PARENTAL_BOND },
  [SpeciesId.RHYHORN]: { 0: AbilityId.SOLID_ROCK },
  [SpeciesId.RHYDON]: { 0: AbilityId.SOLID_ROCK },
  [SpeciesId.RHYPERIOR]: { 0: AbilityId.FILTER },
  [SpeciesId.TANGELA]: { 0: AbilityId.SEED_SOWER },
  [SpeciesId.TANGROWTH]: { 0: AbilityId.SEED_SOWER },
  [SpeciesId.KANGASKHAN]: { 0: AbilityId.TECHNICIAN, 1: AbilityId.TECHNICIAN },
  [SpeciesId.HORSEA]: { 0: AbilityId.DRAGONS_MAW },
  [SpeciesId.SEADRA]: { 0: AbilityId.DRAGONS_MAW },
  [SpeciesId.KINGDRA]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.GOLDEEN]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.SEAKING]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.STARYU]: { 0: AbilityId.REGENERATOR },
  [SpeciesId.STARMIE]: { 0: AbilityId.REGENERATOR },
  [SpeciesId.SCYTHER]: { 0: AbilityId.TINTED_LENS },
  [SpeciesId.SCIZOR]: { 0: AbilityId.TOUGH_CLAWS, 1: AbilityId.TOUGH_CLAWS },
  [SpeciesId.KLEAVOR]: { 0: AbilityId.WEAK_ARMOR },
  [SpeciesId.PINSIR]: { 0: AbilityId.TINTED_LENS, 1: AbilityId.MOLD_BREAKER },
  [SpeciesId.TAUROS]: { 0: AbilityId.STAMINA },
  [SpeciesId.MAGIKARP]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.GYARADOS]: { 0: AbilityId.MULTISCALE, 1: AbilityId.MULTISCALE },
  [SpeciesId.LAPRAS]: { 0: AbilityId.FILTER, 1: AbilityId.FILTER },
  [SpeciesId.DITTO]: { 0: AbilityId.ADAPTABILITY },
  [SpeciesId.EEVEE]: { 0: AbilityId.PICKUP, 1: AbilityId.PICKUP, 2: AbilityId.FLUFFY },
  [SpeciesId.VAPOREON]: { 0: AbilityId.REGENERATOR },
  [SpeciesId.JOLTEON]: { 0: AbilityId.TRANSISTOR },
  [SpeciesId.FLAREON]: { 0: AbilityId.FUR_COAT },
  [SpeciesId.ESPEON]: { 0: AbilityId.MAGICIAN },
  [SpeciesId.UMBREON]: { 0: AbilityId.TOXIC_CHAIN },
  [SpeciesId.LEAFEON]: { 0: AbilityId.GRASSY_SURGE },
  [SpeciesId.GLACEON]: { 0: AbilityId.SNOW_WARNING },
  [SpeciesId.SYLVEON]: { 0: AbilityId.COMPETITIVE },
  [SpeciesId.PORYGON]: { 0: AbilityId.TRANSISTOR },
  [SpeciesId.PORYGON2]: { 0: AbilityId.TRANSISTOR },
  [SpeciesId.PORYGON_Z]: { 0: AbilityId.PROTEAN },
  [SpeciesId.OMANYTE]: { 0: AbilityId.STURDY },
  [SpeciesId.OMASTAR]: { 0: AbilityId.STURDY },
  [SpeciesId.KABUTO]: { 0: AbilityId.TOUGH_CLAWS },
  [SpeciesId.KABUTOPS]: { 0: AbilityId.TOUGH_CLAWS },
  [SpeciesId.AERODACTYL]: { 0: AbilityId.INTIMIDATE, 1: AbilityId.ROCKY_PAYLOAD },
  [SpeciesId.ARTICUNO]: { 0: AbilityId.SNOW_WARNING },
  [SpeciesId.ZAPDOS]: { 0: AbilityId.DRIZZLE },
  [SpeciesId.MOLTRES]: { 0: AbilityId.DROUGHT },
  [SpeciesId.DRATINI]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.DRAGONAIR]: { 0: AbilityId.MULTISCALE },
  [SpeciesId.DRAGONITE]: { 0: AbilityId.AERILATE },
  [SpeciesId.MEWTWO]: { 0: AbilityId.NEUROFORCE, 1: AbilityId.NEUROFORCE, 2: AbilityId.NEUROFORCE },
  [SpeciesId.MEW]: { 0: AbilityId.PROTEAN },
};