export const pokerogue_pokemonEggMoves_Sinnoh = {
  turtwig: ["Shell Smash", "Stone Axe", "Ice Spinner", "Sappy Seed"],
  chimchar: ["Thunderbolt", "Secret Sword", "Ice Punch", "Sacred Fire"],
  piplup: ["Kings Shield", "Tachyon Cutter", "Freeze Dry", "Steam Eruption"],
  starly: ["Swords Dance", "Head Charge", "Flare Blitz", "Extreme Speed"],
  bidoof: ["Extreme Speed", "Cosmic Power", "Power Trip", "Aqua Step"],
  kricketot: ["Bonemerang", "Victory Dance", "Stone Axe", "Population Bomb"],
  shinx: ["Thunderous Kick", "Triple Axel", "Zippy Zap", "Bolt Strike"],
  budew: ["Fiery Dance", "Acid Spray", "Bouncy Bubble", "Quiver Dance"],
  cranidos: ["Volt Tackle", "Accelerock", "Flare Blitz", "Shift Gear"],
  shieldon: ["Shore Up", "Body Press", "Kings Shield", "Diamond Storm"],
  burmy: ["Fiery Dance", "Defend Order", "Heal Order", "Sappy Seed"],
  combee: ["Spore", "Floaty Fall", "Kings Shield", "Victory Dance"],
  pachirisu: ["Freezy Frost", "Sizzly Slide", "Slack Off", "Thunder Cage"],
  buizel: ["Jet Punch", "Triple Axel", "Supercell Slam", "Surging Strikes"],
  cherubi: ["Sleep Powder", "Strength Sap", "Fire Lash", "Flower Trick"],
  shellos: ["Bouncy Bubble", "Scorching Sands", "Freeze Dry", "Steam Eruption"],
  drifloon: ["Psycho Shift", "Mind Blown", "Calm Mind", "Oblivion Wing"],
  buneary: ["Triple Axel", "Extreme Speed", "Thunderous Kick", "Swords Dance"],
  glameow: ["Parting Shot", "High Horsepower", "Swords Dance", "Extreme Speed"],
  chingling: ["Alluring Voice", "Eerie Spell", "Torch Song", "Boomburst"],
  stunky: ["Ceaseless Edge", "Fire Lash", "Recover", "Dire Claw"],
  bronzor: ["Recover", "Tachyon Cutter", "Glare", "Lumina Crash"],
  bonsly: ["Accelerock", "Swords Dance", "Strength Sap", "Sappy Seed"],
  mime_jr: ["Chilly Reception", "Moonblast", "Frost Breath", "Lumina Crash"],
  happiny: ["Cotton Guard", "Seismic Toss", "Sizzly Slide", "Revival Blessing"],
  chatot: ["Sparkling Aria", "Boomburst", "Baton Pass", "Torch Song"],
  spiritomb: ["Parting Shot", "Baddy Bad", "Bitter Malice", "Strength Sap"],
  gible: ["Meteor Mash", "Bitter Blade", "Lands Wrath", "Dragon Dance"],
  munchlax: ["Obstruct", "Grav Apple", "Sucker Punch", "Slack Off"],
  riolu: ["Thunderous Kick", "Tachyon Cutter", "Triple Axel", "Sunsteel Strike"],
  hippopotas: ["Shore Up", "Stone Axe", "Bulk Up", "Salt Cure"],
  skorupi: ["Coil", "Dire Claw", "Crabhammer", "Wicked Blow"],
  croagunk: ["Dire Claw", "Triple Axel", "Thunderous Kick", "Victory Dance"],
  carnivine: ["Strength Sap", "Fire Lash", "Coil", "Sappy Seed"],
  finneon: ["Quiver Dance", "Splishy Splash", "Freeze Dry", "Oblivion Wing"],
  mantyke: ["Splishy Splash", "Freezy Frost", "Nasty Plot", "Oblivion Wing"],
  snover: ["Lands Wrath", "Powder", "Calm Mind", "Matcha Gotcha"],
  rotom: ["Strength Sap", "Fiery Dance", "Splishy Splash", "Electro Drift"],
  uxie: ["Lumina Crash", "Aura Sphere", "Recover", "Tail Glow"],
  mesprit: ["Photon Geyser", "Aura Sphere", "Recover", "Tail Glow"],
  azelf: ["Psystrike", "Aura Sphere", "Ice Beam", "Tail Glow"],
  dialga: ["Core Enforcer", "Take Heart", "Recover", "Make It Rain"],
  palkia: ["Malignant Chain", "Take Heart", "Recover", "Origin Pulse"],
  heatran: ["Energy Ball", "Recover", "Eruption", "Tachyon Cutter"],
  regigigas: ["Obstruct", "Recover", "Storm Throw", "Lands Wrath"],
  giratina: ["Dragon Dance", "Spectral Thief", "Recover", "Collision Course"],
  cresselia: ["Cosmic Power", "Body Press", "Sizzly Slide", "Lumina Crash"],
  phione: ["Bouncy Bubble", "Freeze Dry", "Stored Power", "Origin Pulse"],
  manaphy: ["Bouncy Bubble", "Frost Breath", "Wildbolt Storm", "Origin Pulse"],
  darkrai: ["Fiery Wrath", "Moonblast", "Fiery Dance", "Make It Rain"],
  shaymin: ["Matcha Gotcha", "Heat Wave", "Aeroblast", "Quiver Dance"],
  arceus: ["No Retreat", "Collision Course", "Astral Barrage", "Multi Attack"]
};