export const pokerogue_pokemonEggMoves_Unova  = {
  victini: ["Blue Flare", "Bolt Strike", "Luster Purge", "Victory Dance"],
  snivy: ["Burning Jealousy", "Leech Life", "Superpower", "Draco Meteor"],
  tepig: ["Wave Crash", "Volt Tackle", "Axe Kick", "Victory Dance"],
  oshawott: ["Freeze Dry", "Shell Side Arm", "Sacred Sword", "Shell Smash"],
  patrat: ["Fake Out", "Instruct", "Dynamic Punch", "Extreme Speed"],
  lillipup: ["Close Combat", "Body Slam", "High Horsepower", "Last Respects"],
  purrloin: ["Encore", "Obstruct", "Parting Shot", "Wicked Blow"],
  pansage: ["Swords Dance", "Fire Lash", "Earthquake", "Ivy Cudgel"],
  pansear: ["Nasty Plot", "Hydro Steam", "Earth Power", "Eruption"],
  panpour: ["Nasty Plot", "Energy Ball", "Earth Power", "Water Spout"],
  munna: ["Cosmic Power", "Aura Sphere", "Lunar Blessing", "Mystical Power"],
  pidove: ["Slash", "Tidy Up", "Floaty Fall", "Triple Arrows"],
  blitzle: ["Horn Leech", "Swords Dance", "Flare Blitz", "Bolt Strike"],
  roggenrola: ["Body Press", "Spiky Shield", "Shore Up", "Diamond Storm"],
  woobat: ["Esper Wing", "Stored Power", "Mystical Fire", "Oblivion Wing"],
  drilbur: ["Meteor Mash", "Ice Spinner", "Shift Gear", "Thousand Arrows"],
  audino: ["Take Heart", "Moonblast", "Wish", "Matcha Gotcha"],
  timburr: ["Mach Punch", "Drain Punch", "Ice Hammer", "Double Iron Bash"],
  tympole: ["Jet Punch", "High Horsepower", "Bulk Up", "Surging Strikes"],
  throh: ["Mach Punch", "Slack Off", "Meteor Mash", "Rage Fist"],
  sawk: ["Drain Punch", "Sucker Punch", "Meteor Mash", "Victory Dance"],
  sewaddle: ["Stone Axe", "Psycho Cut", "Bitter Blade", "Victory Dance"],
  venipede: ["Baneful Bunker", "Leech Life", "Noxious Torque", "Power Trip"],
  cottonee: ["Pollen Puff", "Parting Shot", "Sleep Powder", "Seed Flare"],
  petilil: ["Thunderous Kick", "Sparkling Aria", "Fiery Dance", "Flower Trick"],
  basculin: ["Last Respects", "Close Combat", "Splishy Splash", "No Retreat"],
  sandile: ["Dire Claw", "Sucker Punch", "Fire Lash", "Headlong Rush"],
  darumaka: ["Drain Punch", "Zippy Zap", "Headlong Rush", "Pyro Ball"],
  maractus: ["Earth Power", "Sizzly Slide", "Fiery Dance", "Quiver Dance"],
  dwebble: ["Crabhammer", "Stone Axe", "Leech Life", "Mighty Cleave"],
  scraggy: ["Sucker Punch", "Slack Off", "Gunk Shot", "Thunderous Kick"],
  sigilyph: ["Moonblast", "Psycho Shift", "Esper Wing", "Oblivion Wing"],
  yamask: ["Strength Sap", "Glare", "Aura Sphere", "Astral Barrage"],
  tirtouga: ["Ice Spinner", "Aqua Step", "Shore Up", "Mighty Cleave"],
  archen: ["Roost", "Earthquake", "Floaty Fall", "Mighty Cleave"],
  trubbish: ["Coil", "Recover", "Dire Claw", "Gigaton Hammer"],
  zorua: ["Malignant Chain", "Moonblast", "Secret Sword", "Fiery Wrath"],
  minccino: ["Icicle Spear", "Tidy Up", "Low Kick", "Population Bomb"],
  gothita: ["Recover", "Moonblast", "Aura Sphere", "Lumina Crash"],
  solosis: ["Mist Ball", "Speed Swap", "Flamethrower", "Light Of Ruin"],
  ducklett: ["Splishy Splash", "Sandsear Storm", "Wildbolt Storm", "Quiver Dance"],
  vanillite: ["Earth Power", "Aurora Veil", "Calm Mind", "Sparkly Swirl"],
  deerling: ["Tidy Up", "Headbutt", "Axe Kick", "Flower Trick"],
  emolga: ["Icicle Crash", "Zing Zap", "Floaty Fall", "Electrify"],
  karrablast: ["Leech Life", "Bitter Blade", "Obstruct", "Double Iron Bash"],
  foongus: ["Pollen Puff", "Parting Shot", "Foul Play", "Sappy Seed"],
  frillish: ["Calm Mind", "Buzzy Buzz", "Freeze Dry", "Steam Eruption"],
  alomomola: ["Flip Turn", "Heart Swap", "Glitzy Glow", "Revival Blessing"],
  joltik: ["Wildbolt Storm", "Parabolic Charge", "Earth Power", "Quiver Dance"],
  ferroseed: ["Synthesis", "Ceaseless Edge", "Spiky Shield", "Sappy Seed"],
  klink: ["Triple Axel", "High Horsepower", "Recover", "Aura Wheel"],
  tynamo: ["Scald", "Strength Sap", "Fire Lash", "Aura Wheel"],
  elgyem: ["Thunderclap", "Baddy Bad", "Aura Sphere", "Photon Geyser"],
  litwick: ["Giga Drain", "Earth Power", "Moonblast", "Torch Song"],
  axew: ["Stone Axe", "Dire Claw", "Raging Fury", "Bitter Blade"],
  cubchoo: ["Mountain Gale", "Aqua Step", "Ice Shard", "Collision Course"],
  cryogonal: ["Freezing Glare", "Aurora Veil", "Nasty Plot", "Origin Pulse"],
  shelmet: ["Power Gem", "Nasty Plot", "Earth Power", "Steam Eruption"],
  stunfisk: ["Thunderclap", "Sandsear Storm", "Strength Sap", "Thunder Cage"],
  mienfoo: ["Gunk Shot", "Supercell Slam", "Mountain Gale", "Wicked Blow"],
  druddigon: ["Fire Lash", "Morning Sun", "Dragon Darts", "Clangorous Soul"],
  golett: ["Shift Gear", "Drain Punch", "Headlong Rush", "Rage Fist"],
  pawniard: ["Sucker Punch", "Spirit Break", "Last Respects", "Bitter Blade"],
  bouffalant: ["Horn Leech", "High Jump Kick", "Head Smash", "Flare Blitz"],
  rufflet: ["Floaty Fall", "Aura Sphere", "Drill Run", "No Retreat"],
  vullaby: ["Foul Play", "Body Press", "Roost", "Ruination"],
  heatmor: ["Earth Power", "Overheat", "Supercell Slam", "V Create"],
  durant: ["High Horsepower", "First Impression", "U Turn", "Behemoth Bash"],
  deino: ["Fiery Wrath", "Esper Wing", "Sludge Bomb", "Fickle Beam"],
  larvesta: ["Thunderbolt", "Dazzling Gleam", "Scald", "Sandsear Storm"],
  cobalion: ["Behemoth Blade", "Mighty Cleave", "Ceaseless Edge", "Victory Dance"],
  terrakion: ["Mighty Cleave", "Headlong Rush", "Knock Off", "Victory Dance"],
  virizion: ["Sappy Seed", "Psyblade", "Stone Axe", "Victory Dance"],
  tornadus: ["Sandsear Storm", "Parting Shot", "Splishy Splash", "Oblivion Wing"],
  thundurus: ["Sandsear Storm", "Hurricane", "Frost Breath", "Electro Shot"],
  reshiram: ["Energy Ball", "Take Heart", "Fickle Beam", "Eruption"],
  zekrom: ["Triple Axel", "Thunderous Kick", "Dragon Hammer", "Dragon Energy"],
  landorus: ["Stone Axe", "Floaty Fall", "Roost", "Thousand Waves"],
  kyurem: ["Dragon Darts", "Glacial Lance", "No Retreat", "Dragon Energy"],
  keldeo: ["Bouncy Bubble", "Thunderbolt", "Ice Beam", "Steam Eruption"],
  meloetta: ["Body Slam", "Psychic Noise", "Triple Arrows", "Torch Song"],
  genesect: ["Extreme Speed", "Shift Gear", "Behemoth Bash", "Tachyon Cutter"]
}