export const pokerogue_pokemonEggMoves_Kanto = {
  bulbasaur: ["Sappy Seed", "Malignant Chain", "Earth Power", "Matcha Gotcha"],
  charmander: ["Dragon Dance", "Aeroblast", "Earth Power", "Bitter Blade"],
  squirtle: ["Freeze Dry", "Armor Cannon", "Shore Up", "Origin Pulse"],
  caterpie: ["Sandsear Storm", "Silk Trap", "Twin Beam", "Bleakwind Storm"],
  weedle: ["Thousand Arrows", "Noxious Torque", "Attack Order", "Victory Dance"],
  pidgey: ["Bleakwind Storm", "Focus Blast", "Calm Mind", "Boomburst"],
  rattata: ["Hyper Fang", "Psychic Fangs", "Fire Fang", "Extreme Speed"],
  spearow: ["Floaty Fall", "Hyper Drill", "Swords Dance", "Triple Arrows"],
  ekans: ["Noxious Torque", "Dragon Dance", "Slack Off", "Shed Tail"],
  sandshrew: ["High Horsepower", "Dire Claw", "Shore Up", "Mighty Cleave"],
  nidoran_f: ["Baneful Bunker", "Moonlight", "Barb Barrage", "Thousand Waves"],
  nidoran_m: ["Dragon Dance", "Mountain Gale", "Noxious Torque", "Precipice Blades"],
  vulpix: ["Moonblast", "Infernal Parade", "Morning Sun", "Tail Glow"],
  zubat: ["Floaty Fall", "Dire Claw", "Swords Dance", "Collision Course"],
  oddish: ["Sludge Bomb", "Fiery Dance", "Strength Sap", "Spore"],
  paras: ["Leech Life", "Horn Leech", "Crabhammer", "Sappy Seed"],
  venonat: ["Sludge Bomb", "Toxic Thread", "Earth Power", "Stored Power"],
  diglett: ["Triple Dive", "Swords Dance", "Triple Axel", "Headlong Rush"],
  meowth: ["Heart Stamp", "Swords Dance", "Sizzly Slide", "Tail Slap"],
  psyduck: ["Frost Breath", "Aqua Step", "Mystical Power", "Bouncy Bubble"],
  mankey: ["Drain Punch", "Slack Off", "Meteor Mash", "No Retreat"],
  growlithe: ["Zing Zap", "Dragon Dance", "Morning Sun", "Sacred Fire"],
  poliwag: ["Slack Off", "Wildbolt Storm", "Drain Punch", "Surging Strikes"],
  abra: ["Aura Sphere", "Baddy Bad", "Ice Beam", "Psystrike"],
  machop: ["Drain Punch", "Meteor Mash", "Mountain Gale", "Fissure"],
  bellsprout: ["Solar Blade", "Strength Sap", "Fire Lash", "Victory Dance"],
  tentacool: ["Baneful Bunker", "Malignant Chain", "Bouncy Bubble", "Strength Sap"],
  geodude: ["Flare Blitz", "Head Smash", "Shore Up", "Shell Smash"],
  ponyta: ["Headlong Rush", "High Jump Kick", "Swords Dance", "Volt Tackle"],
  slowpoke: ["Splishy Splash", "Frost Breath", "Shed Tail", "Mystical Power"],
  magnemite: ["Parabolic Charge", "Flamethrower", "Thunderclap", "Ice Beam"],
  farfetchd: ["Ivy Cudgel", "Triple Arrows", "Drill Run", "Victory Dance"],
  doduo: ["Triple Axel", "Hyper Drill", "Floaty Fall", "Triple Arrows"],
  seel: ["Freeze Dry", "Bouncy Bubble", "Slack Off", "Steam Eruption"],
  grimer: ["Sucker Punch", "Curse", "Noxious Torque", "Strength Sap"],
  shellder: ["Rock Blast", "Water Shuriken", "Freeze Dry", "Bone Rush"],
  gastly: ["Malignant Chain", "Aura Sphere", "Parting Shot", "Dark Void"],
  onix: ["Shore Up", "Thousand Waves", "Coil", "Diamond Storm"],
  drowzee: ["Baddy Bad", "Strength Sap", "Lumina Crash", "Dark Void"],
  krabby: ["Dire Claw", "Dragon Hammer", "Ivy Cudgel", "Jet Punch"],
  voltorb: ["Nasty Plot", "Fusion Flare", "Energy Ball", "Electro Drift"],
  exeggcute: ["Fickle Beam", "Apple Acid", "Heat Wave", "Lumina Crash"],
  cubone: ["Head Smash", "Wood Hammer", "Shadow Sneak", "Bitter Blade"],
  lickitung: ["Crush Grip", "Fire Lash", "Slack Off", "Magical Torque"],
  koffing: ["Scald", "Recover", "Body Press", "Malignant Chain"],
  rhyhorn: ["Shore Up", "Ice Hammer", "Accelerock", "Head Smash"],
  tangela: ["Natures Madness", "Snap Trap", "Parting Shot", "Sappy Seed"],
  kangaskhan: ["Power Up Punch", "Trailblaze", "Covet", "Seismic Toss"],
  horsea: ["Snipe Shot", "Take Heart", "Shell Side Arm", "Dragon Energy"],
  goldeen: ["Glacial Lance", "Supercell Slam", "Dragon Dance", "Fishious Rend"],
  staryu: ["Calm Mind", "Bouncy Bubble", "Moonblast", "Mystical Power"],
  scyther: ["Mighty Cleave", "Gear Grind", "Storm Throw", "Bitter Blade"],
  pinsir: ["Headlong Rush", "Leech Life", "Crush Grip", "Extreme Speed"],
  tauros: ["Swords Dance", "Fire Lash", "Wicked Torque", "Collision Course"],
  magikarp: ["Flip Turn", "Ice Spinner", "Knock Off", "Dragon Ascent"],
  lapras: ["Recover", "Freeze Dry", "Scald", "Shell Smash"],
  ditto: ["Mimic", "Sketch", "Metronome", "Imprison"],
  eevee: ["Wish", "No Retreat", "Zippy Zap", "Boomburst"],
  porygon: ["Thunderclap", "Dazzling Gleam", "Flamethrower", "Techno Blast"],
  omanyte: ["Freeze Dry", "Giga Drain", "Power Gem", "Steam Eruption"],
  kabuto: ["Ceaseless Edge", "High Horsepower", "Mighty Cleave", "Crabhammer"],
  aerodactyl: ["Acrobatics", "High Horsepower", "Stone Axe", "Swords Dance"],
  articuno: ["Earth Power", "Calm Mind", "Aurora Veil", "Aeroblast"],
  zapdos: ["Bleakwind Storm", "Calm Mind", "Sandsear Storm", "Electro Shot"],
  moltres: ["Earth Power", "Calm Mind", "Aeroblast", "Torch Song"],
  dratini: ["Dragon Hammer", "Crush Grip", "Fire Lash", "Gigaton Hammer"],
  mewtwo: ["Meteor Mash", "Moonblast", "Thunderous Kick", "Photon Geyser"],
  mew: ["Photon Geyser", "Moonblast", "Astral Barrage", "Shell Smash"]
};