export const pokerogue_pokemonEggMoves_Jotho = {
  chikorita: ["Sappy Seed", "Stone Axe", "Dragon Dance", "Spore"],
  cyndaquil: ["Burning Bulwark", "Earth Power", "Fiery Dance", "Electro Drift"],
  totodile: ["Thunder Fang", "Dragon Dance", "Drain Punch", "Surging Strikes"],
  sentret: ["Tidy Up", "Fake Out", "Nuzzle", "Extreme Speed"],
  hoothoot: ["Take Heart", "Esper Wing", "Aeroblast", "Boomburst"],
  ledyba: ["Pollen Puff", "Mat Block", "Parting Shot", "Spore"],
  spinarak: ["Parting Shot", "Attack Order", "Gastro Acid", "Strength Sap"],
  chinchou: ["Thunderclap", "Bouncy Bubble", "Thunder Cage", "Tail Glow"],
  pichu: ["Moonblast", "Triple Axel", "Fiery Dance", "Aura Wheel"],
  cleffa: ["Calm Mind", "Earth Power", "Lunar Blessing", "Light Of Ruin"],
  igglybuff: ["Drain Punch", "Grav Apple", "Soft Boiled", "Extreme Speed"],
  togepi: ["Scorching Sands", "Splishy Splash", "Relic Song", "Fiery Dance"],
  natu: ["Revival Blessing", "Nasty Plot", "Moonblast", "Oblivion Wing"],
  mareep: ["Flamethrower", "Parabolic Charge", "Core Enforcer", "Tail Glow"],
  hoppip: ["Floaty Fall", "Strength Sap", "Sappy Seed", "Spore"],
  aipom: ["Rock Blast", "Storm Throw", "Fake Out", "Swords Dance"],
  sunkern: ["Spore", "Quiver Dance", "Fiery Dance", "Hydro Steam"],
  yanma: ["Nasty Plot", "Earth Power", "Heat Wave", "Bleakwind Storm"],
  wooper: ["Sizzly Slide", "Recover", "Shed Tail", "Surging Strikes"],
  murkrow: ["Cross Chop", "Floaty Fall", "Tidy Up", "Wicked Blow"],
  misdreavus: ["Take Heart", "Moonblast", "Aura Sphere", "Moongeist Beam"],
  unown: ["Nature Power", "Cosmic Power", "Ancient Power", "Mystical Power"],
  girafarig: ["Mystical Power", "Night Daze", "Recover", "Boomburst"],
  pineco: ["Metal Burst", "Recover", "Leech Life", "Spin Out"],
  dunsparce: ["Wicked Torque", "Magical Torque", "Blazing Torque", "Extreme Speed"],
  gligar: ["Fly", "Thousand Waves", "Baneful Bunker", "Mighty Cleave"],
  snubbull: ["Facade", "High Horsepower", "Swords Dance", "Extreme Speed"],
  qwilfish: ["Barb Barrage", "Baneful Bunker", "Recover", "Fishious Rend"],
  shuckle: ["Stuff Cheeks", "Heal Order", "Body Press", "Salt Cure"],
  heracross: ["Rock Blast", "Storm Throw", "Icicle Spear", "Scale Shot"],
  sneasel: ["Dire Claw", "Darkest Lariat", "Triple Axel", "Close Combat"],
  teddiursa: ["Mountain Gale", "Fake Out", "Slack Off", "Precipice Blades"],
  slugma: ["Burning Bulwark", "Power Gem", "Solar Beam", "Magma Storm"],
  swinub: ["Slack Off", "Mountain Gale", "Stone Axe", "Precipice Blades"],
  corsola: ["Scald", "Freeze Dry", "Strength Sap", "Salt Cure"],
  remoraid: ["Water Shuriken", "Take Heart", "Shell Side Arm", "Bouncy Bubble"],
  delibird: ["Bonemerang", "Floaty Fall", "Victory Dance", "Glacial Lance"],
  skarmory: ["Roost", "Body Press", "Ceaseless Edge", "Beak Blast"],
  houndour: ["Fiery Wrath", "Thunderbolt", "Moonblast", "Armor Cannon"],
  phanpy: ["Shore Up", "Swords Dance", "Mountain Gale", "Collision Course"],
  stantler: ["Thunderous Kick", "Photon Geyser", "Swords Dance", "Boomburst"],
  smeargle: ["Conversion", "Burning Bulwark", "Salt Cure", "Dark Void"],
  tyrogue: ["Darkest Lariat", "Thunderous Kick", "Meteor Mash", "Victory Dance"],
  smoochum: ["Luster Purge", "Aura Sphere", "Freeze Dry", "Quiver Dance"],
  elekid: ["Fire Lash", "Zing Zap", "Mountain Gale", "Shift Gear"],
  magby: ["Thunderclap", "Earth Power", "Energy Ball", "Blue Flare"],
  miltank: ["Body Press", "Bulk Up", "Knock Off", "Sizzly Slide"],
  raikou: ["Parabolic Charge", "Nasty Plot", "Frost Breath", "Electro Drift"],
  entei: ["Burning Bulwark", "Dragon Dance", "Earthquake", "Pyro Ball"],
  suicune: ["Recover", "Nasty Plot", "Freeze Dry", "Steam Eruption"],
  larvitar: ["Dragon Dance", "Mountain Gale", "Shore Up", "Diamond Storm"],
  lugia: ["Nasty Plot", "Lumina Crash", "Aura Sphere", "Oblivion Wing"],
  ho_oh: ["Brave Bird", "Dragon Dance", "Revival Blessing", "Bolt Beak"],
  celebi: ["Photon Geyser", "Matcha Gotcha", "Revival Blessing", "Quiver Dance"]
}