export const pokerogue_pokemonEggMoves_Galar = {
  grookey: ["Rock Slide", "Play Rough", "Grassy Glide", "Clangorous Soul"],
  scorbunny: ["Extreme Speed", "High Jump Kick", "Supercell Slam", "Triple Axel"],
  sobble: ["Aeroblast", "Frost Breath", "Energy Ball", "Nasty Plot"],
  skwovet: ["Sucker Punch", "Slack Off", "Coil", "Population Bomb"],
  rookidee: ["Roost", "Body Press", "Kings Shield", "Behemoth Bash"],
  blipbug: ["Heal Order", "Luster Purge", "Sleep Powder", "Tail Glow"],
  nickit: ["Baddy Bad", "Mystical Fire", "Sparkly Swirl", "Make It Rain"],
  gossifleur: ["Baton Pass", "Tailwind", "Sappy Seed", "Spore"],
  wooloo: ["Nuzzle", "Milk Drink", "Body Press", "Multi Attack"],
  chewtle: ["Ice Fang", "Psychic Fangs", "Shell Smash", "Mighty Cleave"],
  yamper: ["Ice Fang", "Swords Dance", "Thunder Fang", "Bolt Strike"],
  rolycoly: ["Blazing Torque", "Burning Bulwark", "Recover", "Diamond Storm"],
  applin: ["Core Enforcer", "Combat Torque", "Sappy Seed", "Matcha Gotcha"],
  silicobra: ["Shore Up", "Shed Tail", "Mountain Gale", "Thousand Arrows"],
  cramorant: ["Apple Acid", "Surf", "Bolt Beak", "Oblivion Wing"],
  arrokuda: ["Supercell Slam", "Triple Dive", "Ice Spinner", "Swords Dance"],
  toxel: ["Buzzy Buzz", "Bug Buzz", "Sparkling Aria", "Torch Song"],
  sizzlipede: ["Burning Bulwark", "Zing Zap", "First Impression", "Bitter Blade"],
  clobbopus: ["Storm Throw", "Jet Punch", "Mach Punch", "Surging Strikes"],
  sinistea: ["Splishy Splash", "Matcha Gotcha", "Draining Kiss", "Moongeist Beam"],
  hatenna: ["Recover", "Moonblast", "Buzzy Buzz", "Torch Song"],
  impidimp: ["Slack Off", "Parting Shot", "Octolock", "Wicked Blow"],
  milcery: ["Moonblast", "Chilly Reception", "Earth Power", "Geomancy"],
  falinks: ["Baton Pass", "Power Trip", "Sacred Sword", "Heal Order"],
  pincurchin: ["Trick Room", "Volt Switch", "Strength Sap", "Thunderclap"],
  snom: ["Frost Breath", "Heal Order", "Earth Power", "Spore"],
  stonjourner: ["Axe Kick", "Helping Hand", "Accelerock", "Diamond Storm"],
  eiscue: ["Triple Axel", "Aqua Step", "Axe Kick", "Shell Smash"],
  indeedee: ["Matcha Gotcha", "Expanding Force", "Moonblast", "Revival Blessing"],
  morpeko: ["Ice Spinner", "Obstruct", "Stuff Cheeks", "Collision Course"],
  cufant: ["Liquidation", "Curse", "Combat Torque", "Gigaton Hammer"],
  dracozolt: ["Triple Axel", "Gunk Shot", "Fire Lash", "Dragon Dance"],
  arctozolt: ["Mountain Gale", "Aqua Step", "High Horsepower", "Shift Gear"],
  dracovish: ["Triple Axel", "Dragon Hammer", "Thunder Fang", "Dragon Dance"],
  arctovish: ["Ice Fang", "Thunder Fang", "High Horsepower", "Shift Gear"],
  duraludon: ["Heat Wave", "Body Press", "Thunderclap", "Core Enforcer"],
  dreepy: ["Shadow Bone", "Power Up Punch", "Fire Lash", "Dire Claw"],
  zacian: ["Magical Torque", "Mighty Cleave", "Earthquake", "Bitter Blade"],
  zamazenta: ["Bulk Up", "Body Press", "Power Trip", "Slack Off"],
  eternatus: ["Body Press", "Nasty Plot", "Malignant Chain", "Dragon Energy"],
  kubfu: ["Meteor Mash", "Drain Punch", "Jet Punch", "Dragon Dance"],
  zarude: ["Leaf Blade", "Headlong Rush", "Wicked Blow", "Victory Dance"],
  regieleki: ["Nasty Plot", "Ice Beam", "Earth Power", "Electro Drift"],
  regidrago: ["Shell Side Arm", "Flamethrower", "Take Heart", "Dragon Darts"],
  glastrier: ["Speed Swap", "Slack Off", "High Horsepower", "Glacial Lance"],
  spectrier: ["Earth Power", "Moonlight", "Aura Sphere", "Astral Barrage"],
  calyrex: ["Sappy Seed", "Recover", "Secret Sword", "Photon Geyser"],
  enamorus: ["Aeroblast", "Thousand Arrows", "Stored Power", "Fleur Cannon"],
  galar_meowth: ["Liquidation", "Horn Leech", "Bullet Punch", "Behemoth Bash"],
  galar_ponyta: ["Magical Torque", "Extreme Speed", "Flare Blitz", "Photon Geyser"],
  galar_slowpoke: ["Shed Tail", "Baddy Bad", "Moonblast", "Photon Geyser"],
  galar_farfetchd: ["Roost", "Sacred Sword", "Kings Shield", "Behemoth Blade"],
  galar_articuno: ["Secret Sword", "Night Daze", "Ice Beam", "Oblivion Wing"],
  galar_zapdos: ["Poison Jab", "Floaty Fall", "Roost", "Bolt Beak"],
  galar_moltres: ["Roost", "Sludge Bomb", "Flamethrower", "Oblivion Wing"],
  galar_corsola: ["Shell Smash", "Aura Sphere", "Infernal Parade", "Astral Barrage"],
  galar_zigzagoon: ["Ceaseless Edge", "Facade", "Parting Shot", "Extreme Speed"],
  galar_darumaka: ["Ice Spinner", "Zing Zap", "Drain Punch", "Pyro Ball"],
  galar_yamask: ["Strength Sap", "Dire Claw", "Thousand Waves", "Spectral Thief"],
  galar_stunfisk: ["Spiky Shield", "Thousand Arrows", "Strength Sap", "Double Iron Bash"],
  hisui_growlithe: ["Wave Crash", "Head Smash", "Volt Tackle", "Dragon Dance"],
  hisui_voltorb: ["Dazzling Gleam", "Leech Seed", "Apple Acid", "Mind Blown"],
  hisui_qwilfish: ["Ceaseless Edge", "Baneful Bunker", "Recover", "Fishious Rend"],
  hisui_sneasel: ["Drain Punch", "Knock Off", "Psychic Fangs", "Triple Axel"],
  hisui_zorua: ["Moonblast", "Secret Sword", "Parting Shot", "Blood Moon"]
};