export const pokerogue_pokemonEggMoves_Hoenn = {
  treecko: ["Nasty Plot", "Clanging Scales", "Secret Sword", "Seed Flare"],
  torchic: ["Thunderous Kick", "Zing Zap", "Burning Bulwark", "Pyro Ball"],
  mudkip: ["Shore Up", "Mountain Gale", "Aqua Step", "Precipice Blades"],
  poochyena: ["Knock Off", "Close Combat", "Dire Claw", "Victory Dance"],
  zigzagoon: ["Extreme Speed", "Nuzzle", "High Horsepower", "Tidy Up"],
  wurmple: ["Baton Pass", "Bleakwind Storm", "Stored Power", "Malignant Chain"],
  lotad: ["Revelation Dance", "Apple Acid", "Ice Beam", "Quiver Dance"],
  seedot: ["Swords Dance", "Sacred Sword", "Kowtow Cleave", "Bitter Blade"],
  taillow: ["Boomburst", "Facade", "Headlong Rush", "No Retreat"],
  wingull: ["Thunder", "Flip Turn", "Calm Mind", "Steam Eruption"],
  ralts: ["Psyblade", "Bitter Blade", "No Retreat", "Boomburst"],
  surskit: ["Pollen Puff", "Fiery Dance", "Bouncy Bubble", "Aeroblast"],
  shroomish: ["Accelerock", "Trailblaze", "Storm Throw", "Sappy Seed"],
  slakoth: ["Entrainment", "Drain Punch", "Parting Shot", "Crush Grip"],
  nincada: ["Bulldoze", "Sticky Web", "Shadow Bone", "Shell Smash"],
  whismur: ["Alluring Voice", "Shift Gear", "Sparkling Aria", "Torch Song"],
  makuhita: ["Combat Torque", "Slack Off", "Heat Crash", "Double Iron Bash"],
  azurill: ["Jet Punch", "Magical Torque", "Swords Dance", "Surging Strikes"],
  nosepass: ["Shore Up", "Body Press", "Calm Mind", "Tachyon Cutter"],
  skitty: ["Thunderous Kick", "Entrainment", "Tidy Up", "V Create"],
  sableye: ["Recover", "Topsy Turvy", "Curse", "Salt Cure"],
  mawile: ["Bullet Punch", "Horn Leech", "Earthquake", "Magical Torque"],
  aron: ["Head Smash", "Body Press", "Shore Up", "Salt Cure"],
  meditite: ["Thunderous Kick", "Sucker Punch", "Bullet Punch", "Photon Geyser"],
  electrike: ["Frost Breath", "Heat Wave", "Nasty Plot", "Electro Drift"],
  plusle: ["Flamethrower", "Glitzy Glow", "Splishy Splash", "Tail Glow"],
  minun: ["Ice Beam", "Baddy Bad", "Sparkly Swirl", "Tail Glow"],
  volbeat: ["Baton Pass", "Sticky Web", "Decorate", "Victory Dance"],
  illumise: ["Parting Shot", "Glitzy Glow", "Powder", "Quiver Dance"],
  gulpin: ["Malignant Chain", "Earth Power", "Calm Mind", "Strength Sap"],
  carvanha: ["Thunder Fang", "Gunk Shot", "Obstruct", "Surging Strikes"],
  wailmer: ["Take Heart", "Comeuppance", "Slack Off", "Steam Eruption"],
  numel: ["Trick Room", "Energy Ball", "Slack Off", "Blue Flare"],
  torkoal: ["Morning Sun", "Burning Bulwark", "Body Press", "Hydro Steam"],
  spoink: ["Aura Sphere", "Milk Drink", "Expanding Force", "Tail Glow"],
  spinda: ["Superpower", "Slack Off", "Fleur Cannon", "V Create"],
  trapinch: ["Fire Lash", "Dragon Darts", "Thousand Arrows", "Dragon Energy"],
  cacnea: ["Earth Power", "Ceaseless Edge", "Night Daze", "Ivy Cudgel"],
  swablu: ["Roost", "Take Heart", "Aeroblast", "Boomburst"],
  zangoose: ["Facade", "High Horsepower", "Extreme Speed", "Tidy Up"],
  seviper: ["Ice Beam", "Bitter Blade", "Sucker Punch", "No Retreat"],
  lunatone: ["Revelation Dance", "Moongeist Beam", "Shell Smash", "Lumina Crash"],
  solrock: ["Mighty Cleave", "Photon Geyser", "Shell Smash", "Sacred Fire"],
  barboach: ["Dragon Dance", "Zing Zap", "Ice Spinner", "Surging Strikes"],
  corphish: ["Ceaseless Edge", "Shell Side Arm", "Sucker Punch", "Jet Punch"],
  baltoy: ["Recover", "Glare", "Ruination", "Mystical Power"],
  lileep: ["Power Gem", "Scald", "Strength Sap", "Sappy Seed"],
  anorith: ["First Impression", "Leech Life", "Dragon Dance", "Mighty Cleave"],
  feebas: ["Calm Mind", "Freeze Dry", "Moonblast", "Steam Eruption"],
  castform: ["Boomburst", "Hydro Steam", "Eruption", "Quiver Dance"],
  kecleon: ["Zippy Zap", "Coil", "Extreme Speed", "Multi Attack"],
  shuppet: ["Storm Throw", "Tidy Up", "Parting Shot", "Spectral Thief"],
  duskull: ["Bulk Up", "Drain Punch", "Recover", "Rage Fist"],
  tropius: ["Stuff Cheeks", "Earth Power", "Apple Acid", "Sappy Seed"],
  absol: ["Kowtow Cleave", "Sacred Sword", "Psyblade", "Bitter Blade"],
  wynaut: ["Recover", "Shed Tail", "Taunt", "Comeuppance"],
  snorunt: ["Sparkly Swirl", "Nasty Plot", "Earth Power", "Blood Moon"],
  spheal: ["Flip Turn", "Freeze Dry", "Slack Off", "Steam Eruption"],
  clamperl: ["Shell Side Arm", "Snipe Shot", "Giga Drain", "Bouncy Bubble"],
  relicanth: ["Dragon Dance", "Shore Up", "Wave Crash", "Diamond Storm"],
  luvdisc: ["Baton Pass", "Heart Swap", "Glitzy Glow", "Revival Blessing"],
  bagon: ["Headlong Rush", "Fire Lash", "Dragon Dance", "Dragon Darts"],
  beldum: ["Headlong Rush", "Drain Punch", "Ice Spinner", "Shift Gear"],
  regirock: ["Stone Axe", "Body Press", "Shore Up", "Salt Cure"],
  regice: ["Earth Power", "Take Heart", "Recover", "Freeze Dry"],
  registeel: ["Body Press", "Sizzly Slide", "Recover", "Gigaton Hammer"],
  latias: ["Core Enforcer", "Fusion Flare", "Sparkly Swirl", "Mystical Power"],
  latios: ["Core Enforcer", "Blue Flare", "Nasty Plot", "Tachyon Cutter"],
  kyogre: ["Recover", "Hurricane", "Freezy Frost", "Wildbolt Storm"],
  groudon: ["Stone Axe", "Solar Blade", "Morning Sun", "Sacred Fire"],
  rayquaza: ["V Create", "Dragon Darts", "Core Enforcer", "Oblivion Wing"],
  jirachi: ["Tachyon Cutter", "Triple Arrows", "Rock Slide", "Shell Smash"],
  deoxys: ["Collision Course", "Fusion Flare", "Parting Shot", "Lumina Crash"]
};